var countries = [{name: "Afghanistan", schengen: false, europe: false},
{name: "Albania", schengen: false, europe: true},
{name: "Algeria", schengen: false, europe: false},
{name: "Andorra", schengen: true, europe: true},
{name: "Angola", schengen: false, europe: false},
{name: "Anguilla", schengen: false, europe: false},
{name: "Antigua & Barbuda", schengen: false, europe: false},
{name: "Argentina", schengen: false, europe: false},
{name: "Armenia", schengen: false, europe: true},
{name: "Australia", schengen: false, europe: false},
{name: "Austria", schengen: true, europe: true},
{name: "Azerbaijan", schengen: false, europe: false},
{name: "Bahamas", schengen: false, europe: false},
{name: "Bahrain", schengen: false, europe: false},
{name: "Bangladesh", schengen: false, europe: false},
{name: "Barbados", schengen: false, europe: false},
{name: "Belarus", schengen: false, europe: true},
{name: "Belgium", schengen: true, europe: true},
{name: "Belize", schengen: false, europe: false},
{name: "Benin", schengen: false, europe: false},
{name: "Bermuda", schengen: false, europe: false},
{name: "Bhutan", schengen: false, europe: false},
{name: "Bolivia", schengen: false, europe: false},
{name: "Bosnia & Herzegovina", schengen: false, europe: true},
{name: "Botswana", schengen: false, europe: false},
{name: "Brazil", schengen: false, europe: false},
{name: "Brunei Darussalam", schengen: false, europe: false},
{name: "Bulgaria", schengen: false, europe: true},
{name: "Burkina Faso", schengen: false, europe: false},
{name: "Myanmar/Burma", schengen: false, europe: false},
{name: "Burundi", schengen: false, europe: false},
{name: "Cambodia", schengen: false, europe: false},
{name: "Cameroon", schengen: false, europe: false},
{name: "Canada", schengen: false, europe: false},
{name: "Cape Verde", schengen: false, europe: false},
{name: "Cayman Islands", schengen: false, europe: false},
{name: "Central African Republic", schengen: false, europe: false},
{name: "Chad", schengen: false, europe: false},
{name: "Chile", schengen: false, europe: false},
{name: "China", schengen: false, europe: false},
{name: "Colombia", schengen: false, europe: false},
{name: "Comoros", schengen: false, europe: false},
{name: "Congo", schengen: false, europe: false},
{name: "Costa Rica", schengen: false, europe: false},
{name: "Croatia", schengen: false, europe: true},
{name: "Cuba", schengen: false, europe: false},
{name: "Cyprus", schengen: false, europe: true},
{name: "Czech Republic", schengen: true, europe: true},
{name: "The Congo", schengen: false, europe: false},
{name: "Denmark", schengen: true, europe: true},
{name: "Djibouti", schengen: false, europe: false},
{name: "Dominica", schengen: false, europe: false},
{name: "Dominican Republic", schengen: false, europe: false},
{name: "Ecuador", schengen: false, europe: false},
{name: "Egypt", schengen: false, europe: false},
{name: "El Salvador", schengen: false, europe: false},
{name: "Equatorial Guinea", schengen: false, europe: false},
{name: "Eritrea", schengen: false, europe: false},
{name: "Estonia", schengen: true, europe: true},
{name: "Ethiopia", schengen: false, europe: false},
{name: "Fiji", schengen: false, europe: false},
{name: "Finland", schengen: true, europe: true},
{name: "France", schengen: true, europe: true},
{name: "French Guiana", schengen: false, europe: false},
{name: "Gabon", schengen: false, europe: false},
{name: "Gambia", schengen: false, europe: false},
{name: "Georgia", schengen: false, europe: true},
{name: "Germany", schengen: true, europe: true},
{name: "Ghana", schengen: false, europe: false},
{name: "Great Britain", schengen: false, europe: true},
{name: "Greece", schengen: true, europe: true},
{name: "Grenada", schengen: false, europe: false},
{name: "Guadeloupe", schengen: false, europe: false},
{name: "Guatemala", schengen: false, europe: false},
{name: "Guinea", schengen: false, europe: false},
{name: "Guinea-Bissau", schengen: false, europe: false},
{name: "Guyana", schengen: false, europe: false},
{name: "Haiti", schengen: false, europe: false},
{name: "Honduras", schengen: false, europe: false},
{name: "Hungary", schengen: true, europe: true},
{name: "Iceland", schengen: true, europe: true},
{name: "India", schengen: false, europe: false},
{name: "Indonesia", schengen: false, europe: false},
{name: "Iran", schengen: false, europe: false},
{name: "Iraq", schengen: false, europe: false},
{name: "Israel and the Occupied Territories", schengen: false, europe: false},
{name: "Italy", schengen: true, europe: true},
{name: "Ivory Coast (Cote d'Ivoire)", schengen: false, europe: false},
{name: "Jamaica", schengen: false, europe: false},
{name: "Japan", schengen: false, europe: false},
{name: "Jordan", schengen: false, europe: false},
{name: "Kazakhstan", schengen: false, europe: false},
{name: "Kenya", schengen: false, europe: false},
{name: "Kosovo", schengen: false, europe: true},
{name: "Kuwait", schengen: false, europe: false},
{name: "Kyrgyz Republic (Kyrgyzstan)", schengen: false, europe: false},
{name: "Laos", schengen: false, europe: false},
{name: "Latvia", schengen: true, europe: true},
{name: "Lebanon", schengen: false, europe: false},
{name: "Lesotho", schengen: false, europe: false},
{name: "Liberia", schengen: false, europe: false},
{name: "Libya", schengen: false, europe: false},
{name: "Liechtenstein", schengen: true, europe: true},
{name: "Lithuania", schengen: true, europe: true},
{name: "Luxembourg", schengen: true, europe: true},
{name: "Macedonia", schengen: false, europe: true},
{name: "Madagascar", schengen: false, europe: false},
{name: "Malawi", schengen: false, europe: false},
{name: "Malaysia", schengen: false, europe: false},
{name: "Maldives", schengen: false, europe: false},
{name: "Mali", schengen: false, europe: false},
{name: "Malta", schengen: true, europe: true},
{name: "Martinique", schengen: false, europe: false},
{name: "Mauritania", schengen: false, europe: false},
{name: "Mauritius", schengen: false, europe: false},
{name: "Mayotte", schengen: false, europe: false},
{name: "Mexico", schengen: false, europe: false},
{name: "Moldova, Republic of", schengen: false, europe: true},
{name: "Monaco", schengen: false, europe: true},
{name: "Mongolia", schengen: false, europe: false},
{name: "Montenegro", schengen: false, europe: true},
{name: "Montserrat", schengen: false, europe: false},
{name: "Morocco", schengen: false, europe: false},
{name: "Mozambique", schengen: false, europe: false},
{name: "Namibia", schengen: false, europe: false},
{name: "Nepal", schengen: false, europe: false},
{name: "Netherlands", schengen: true, europe: true},
{name: "New Zealand", schengen: false, europe: false},
{name: "Nicaragua", schengen: false, europe: false},
{name: "Niger", schengen: false, europe: false},
{name: "Nigeria", schengen: false, europe: false},
{name: "North Korea", schengen: false, europe: false},
{name: "Norway", schengen: true, europe: true},
{name: "Oman", schengen: false, europe: false},
{name: "Pacific Islands", schengen: false, europe: false},
{name: "Pakistan", schengen: false, europe: false},
{name: "Panama", schengen: false, europe: false},
{name: "Papua New Guinea", schengen: false, europe: false},
{name: "Paraguay", schengen: false, europe: false},
{name: "Peru", schengen: false, europe: false},
{name: "Philippines", schengen: false, europe: false},
{name: "Poland", schengen: true, europe: true},
{name: "Portugal", schengen: true, europe: true},
{name: "Puerto Rico", schengen: false, europe: false},
{name: "Qatar", schengen: false, europe: false},
{name: "Reunion", schengen: false, europe: false},
{name: "Romania", schengen: false, europe: true},
{name: "Russian Federation", schengen: false, europe: true},
{name: "Rwanda", schengen: false, europe: false},
{name: "Saint Kitts &Nevis", schengen: false, europe: false},
{name: "Saint Lucia", schengen: false, europe: false},
{name: "Saint Vincent's & Grenadines", schengen: false, europe: false},
{name: "Samoa", schengen: false, europe: false},
{name: "Sao Tome & Principe", schengen: false, europe: false},
{name: "Saudi Arabia", schengen: false, europe: false},
{name: "Senegal", schengen: false, europe: false},
{name: "Serbia", schengen: false, europe: true},
{name: "Seychelles", schengen: false, europe: false},
{name: "Sierra Leone", schengen: false, europe: false},
{name: "Singapore", schengen: false, europe: false},
{name: "Slovakia", schengen: true, europe: true},
{name: "Slovenia", schengen: true, europe: true},
{name: "Solomon Islands", schengen: false, europe: false},
{name: "Somalia", schengen: false, europe: false},
{name: "South Africa", schengen: false, europe: false},
{name: "Korea, South Korea", schengen: false, europe: false},
{name: "South Sudan", schengen: false, europe: false},
{name: "Spain", schengen: true, europe: true},
{name: "Sri Lanka", schengen: false, europe: false},
{name: "Sudan", schengen: false, europe: false},
{name: "Suriname", schengen: false, europe: false},
{name: "Swaziland", schengen: false, europe: false},
{name: "Sweden", schengen: true, europe: true},
{name: "Switzerland", schengen: true, europe: true},
{name: "Syria", schengen: false, europe: false},
{name: "Tajikistan", schengen: false, europe: false},
{name: "Tanzania", schengen: false, europe: false},
{name: "Thailand", schengen: false, europe: false},
{name: "Timor Leste", schengen: false, europe: false},
{name: "Togo", schengen: false, europe: false},
{name: "Trinidad & Tobago", schengen: false, europe: false},
{name: "Tunisia", schengen: false, europe: false},
{name: "Turkey", schengen: false, europe: true},
{name: "Turkmenistan", schengen: false, europe: false},
{name: "Turks & Caicos Islands", schengen: false, europe: false},
{name: "Uganda", schengen: false, europe: false},
{name: "Ukraine", schengen: false, europe: true},
{name: "United Arab Emirates", schengen: false, europe: false},
{name: "United States of America (USA)", schengen: false, europe: false},
{name: "Uruguay", schengen: false, europe: false},
{name: "Uzbekistan", schengen: false, europe: false},
{name: "Venezuela", schengen: false, europe: false},
{name: "Vietnam", schengen: false, europe: false},
{name: "UK Virgin Islands", schengen: false, europe: false},
{name: "US Virgin Islands", schengen: false, europe: false},
{name: "Yemen", schengen: false, europe: false},
{name: "Zambia", schengen: false, europe: false},
{name: "Zimbabwe", schengen: false, europe: false}
]
module.exports = countries